[package]
name = "diehockn-api"
version = "0.1.0"
edition = "2021"

[dependencies]
beacon-calculator = { version = "1.1.0", features = ["serde"] }
hmac = "0.12.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.216"
sha2 = "0.10.8"
